### ISSUE TITLE
META file specification

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#2]
The `README.md` specifies a `META` file. Have we got any specs for that? I assume we want to track roughly the information in the [liboqs docs files][oqsdocs] and the [liboqs `OQS_KEM` and `OQS_SIG` structs][oqsstruct].

[oqsdocs]: https://raw.githubusercontent.com/open-quantum-safe/liboqs/master/docs/algorithms/kem_sidh.md
[oqsstruct]: https://github.com/open-quantum-safe/liboqs/blob/master/src/kem/kyber/kem_kyber.c

Format wise, I would suggest Yaml, because it is both easy to read and easy to parse.

## Example

This suggestion assumes that a single META file will cover multiple parameter sets.

```yaml
name: Kyber
type: KEM
parameter_sets:
  - name: Kyber 512
    version: https://github.com/pq-crystals/kyber/commit/ab996e7460e5356b0e23aa034e7c2fe6922e60e6
    claimed_nist_level: 1
    length_public_key: 736
    length_ciphertext: 800
    # ...
  - name: Kyber 768
    # ...
```

**Comment by thomwiggers** [comment]
We will put the SHA3 hash of output of the tests into the META file to do the functional testing.

**Comment by dstebila** [comment]
I like the idea of using Yaml for the metadata.  @cryptojedi and I had talked about a directory structure which would have different parameterizations in different directories (`crypto_kem/kyber512`, `crypto_kem/kyber768`, etc.) which would necessitate different Yaml files for different parameterizations.  But we should probably plan for metadata about different implementations within the same Yaml file (corresponding to directory structure `crypto_kem/kyber512/clean`, `crypto_kem/kyber512/avx2`, etc.).

**Comment by thomwiggers** [comment]
Perhaps a block like:

```yaml
implementations:
  clean:
    version: bla
    license: CC0
```

But I'm not sure what exactly should go there. For example, `license` should already be specified in a `LICENSE` file in `crypto_kem/kyber512/avx2`.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> I like the idea of using Yaml for the metadata.  @cryptojedi and I had
> talked about a directory structure which would have different
> parameterizations in different directories (`crypto_kem/kyber512`,
> `crypto_kem/kyber768`, etc.) which would necessitate different Yaml
> files for different parameterizations.  But we should probably plan
> for metadata about different implementations within the same Yaml file
> (corresponding to directory structure `crypto_kem/kyber512/clean`,
> `crypto_kem/kyber512/avx2`, etc.).

+1 Yaml for using Yaml. Do we want one file per scheme (e.g., under
crypto_kem/kyber512) or under each implementation (e.g., under
crypto_kem/kyber512/clean)? 

I would not include sizes in the Yaml file; those area already in api.h
and I don't like duplicate information. Do we want to include license
information in there? If yes, this suggests a Yaml file per
implementation.

**Comment by dstebila** [comment]
> I would not include sizes in the Yaml file; those area already in api.h and I don't like duplicate information.

I don't like duplicate information, but I also like machine-readable information, and Yaml is more machine-readable than C preprocessor macros.  Basically I'm thinking of code transformation tools that will generate stuff around PQClean implementations, and they may be easier to do if they get keysizes in Yaml metadata rather than having to extract it from C preprocessor macros.

**Comment by thomwiggers** [comment]
@joostrijneveld proposed verifying the `META.yaml` specified sizes with what's specified in `api.h`. By the way, if we want to do any form of linking, then `#define` macros are not sufficient to keep those values in the code...

**Comment by dstebila** [comment]
And for OQS we had a data structure for each scheme that exposed the constants.

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> @joostrijneveld proposed verifying the `META.yaml` specified sizes
> with what's specified in `api.h`. 

Good idea! Should also check that sizes (except for secret-key size) are
consistent across different implementations. 

Also, we should have a TESTVECTORS file in the scheme directory (e.g.,
crypto_kem/kyber512/TESTVECTORS) that all implementations must match.

> By the way, if we want to do any form of linking, then `#define`
> macros are not sufficient to keep those values in the code...

Any code linking against the .a files needs to include the respective
api.h file to know about the sizes.

**Comment by mkannwischer** [comment]
On Wed, Jan 16, 2019 at 08:16:23AM -0800, cryptojedi wrote:
>
> Also, we should have a TESTVECTORS file in the scheme directory (e.g.,
> crypto_kem/kyber512/TESTVECTORS) that all implementations must match.
>

For some schemes this would get huge and should not be put in git.
Isn't it enough to put a hash of the expected testvectors in the META file
and check against that?

**Comment by dstebila** [comment]
For our purposes, yes, a hash of the expected test vectors would be okay.  But there had been a desire expressed at the workshop last week to have a collection of test vectors, in a reasonable format.  I don't think a hash would not sufficiently helpful to someone else wanting to check their own implementation, because they'd have to reproduce our hashing operation as well.

**Comment by thomwiggers** [comment]
I've written a script that verifies a specification for YAML files. It may appear a bit complicated at first, but it allows you to write a specification of the yaml file and then recursively validates it. The [specification](https://github.com/PQClean/PQClean/blob/8fe988fe5169795683c4418d0ad40f0a244a2ce3/test/check_metadata.py#L21-L47) should pretty much speak for itself. The script should give clear errors.

As an example, this is what the META.yml files should look like from now on:

```
name: Dilithium-III
type: signature
claimed-nist-level: 3
length-public-key: 1472
length-signature: 2701
testvectors-sha256: e1852a975842c44a683c914ed131d95bee9b786c36c41e47bb77d7dd3c0c07be
principal-submitter: Vadim Lyubashevsky
auxiliary-submitters:
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/dilithium/commit/ffa89bdbc12a8ee178ccec4890aeea5449ef937a
```
