### ISSUE TITLE
Are clean implementations compatible with ARM achitecture?

### ISSUE THREAD

**Issue by aabmets** [PQClean/PQClean#547]
@thomwiggers 
When I read the META.yml files of PQ algorithms, Dilithium5 for example, the `clean` section does not specify what operating system or architecture is supported:
```
implementations:
    - name: clean
      version: https://github.com/... via https://github.com/...
    - name: avx2
      version: https://github.com/... via https://github.com/...
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - aes
              - avx2
              - popcnt
    - name: aarch64
      version: https://github.com/...
      supported_platforms:
        - architecture: arm_8
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - asimd      
```
Recently, I got an issue raised in my QuantCrypt project, where the clean binaries were available, but the user was trying to use QuantCrypt on an ARM system. If ARM systems specifically require the use of the `aarch64` C source code, then wouldn't it make sense to specifically list out supported platforms also for the `clean` section, if the `clean` implementation does not support all operating systems or architectures?
