### ISSUE TITLE
Automatically check for char / int

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#79]
As I mentioned in https://github.com/PQClean/PQClean/pull/78#issuecomment-479112814, it turns out to be quite tedious to manually find all non-fixed-size integer types. Perhaps we should consider using something like [pycparser](https://github.com/eliben/pycparser) to search the syntax tree. I played around a bit based on the code in #78, and it turns out to be fairly simple to produce AST fragments that find these issues, e.g.,

```
[...]
      For: 
        DeclList: 
          Decl: i, [], [], []
            TypeDecl: i, []
              IdentifierType: ['int']
```

for [this for-loop](https://github.com/PQClean/PQClean/pull/78/files#diff-522f5174363c09963e6f79b74f7a7c55R213), or e.g. [this function declaration](https://github.com/PQClean/PQClean/pull/78/files#diff-25d475e5cf696f6722d3639cbf5eb6b1R128):

```
  Decl: PQCLEAN_FRODOKEM640SHAKE_CLEAN_pack, [], [], []
    FuncDecl: 
      ParamList: 
        Decl: out, [], [], []
          PtrDecl: []
            TypeDecl: out, []
              IdentifierType: ['unsigned', 'char']
        Decl: outlen, [], [], []
          TypeDecl: outlen, []
            IdentifierType: ['size_t']
[...]
```

This means we would really draw a hard line and make CI fail for any of these types.

Is this something we want to implement (perhaps before explicitly opening up for submissions)?

(Tangentially related to the discussion in #77)
